CREATE SCHEMA sgam;

USE sgam;


CREATE TABLE USR_USUARIO (
  USR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  USR_NOME VARCHAR(20) NOT NULL,
  USR_SENHA VARCHAR(50) NOT NULL,
  CONSTRAINT USR_USUARIO_PK PRIMARY KEY (USR_ID),
  CONSTRAINT USR_NOME_UK UNIQUE KEY (USR_NOME)
);

CREATE TABLE AUT_AUTORIZACAO (
  AUT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  AUT_NOME VARCHAR(20) NOT NULL,
  CONSTRAINT AUT_AUTORIZACAO_PK PRIMARY KEY (AUT_ID),
  CONSTRAINT AUT_NOME_UK UNIQUE KEY (AUT_NOME)
);

CREATE TABLE UAU_USUARIO_AUTORIZACAO (
  USR_ID BIGINT UNSIGNED NOT NULL,
  AUT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (USR_ID, AUT_ID),
  FOREIGN KEY UAU_USUARIO_FK (USR_ID) REFERENCES USR_USUARIO (USR_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY UAU_AUTORIZACAO_FK (AUT_ID) REFERENCES AUT_AUTORIZACAO (AUT_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE EMP_EMPRESA(
  EMP_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  EMP_CNPJ INT(20),
  EMP_RAZAO VARCHAR(255),
  CONSTRAINT EMP_EMPRESA_PK PRIMARY KEY (EMP_ID)
);

CREATE TABLE DEP_DEPOSITO(
	DEP_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	DEP_NOME VARCHAR(255),
	EMP_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT DEP_DEPOSITO_PK PRIMARY KEY (DEP_ID),
	FOREIGN KEY EMP_EMPRESA_FK (EMP_ID) REFERENCES EMP_EMPRESA (EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE PPR_PARAMETRO_PROJETO(
 PPR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 PPR_RUA INT,
 PPR_ESTANTE INT,
 PPR_PRATELEIRA INT,
 PPR_PV INT,
 PPR_PH INT, 
 DEP_ID BIGINT UNSIGNED NOT NULL,
 CONSTRAINT PPR_PARAMETRO_PROJETO_PK PRIMARY KEY (PPR_ID),
 FOREIGN KEY DEP_DEPOSITO_FK (DEP_ID) REFERENCES DEP_DEPOSITO (DEP_ID) ON DELETE RESTRICT ON UPDATE CASCADE 
);

CREATE TABLE ARQ_ARQUIVO(
	ARQ_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	ARQ_TIPO VARCHAR(255),
	ARQ_GRUPO VARCHAR(255),
	ARQ_SUB_GRUPO VARCHAR(255),
	EMP_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT ARQ_ARQUIVO_PK PRIMARY KEY (ARQ_ID),
	FOREIGN KEY EMP_EMPRESA_FK (EMP_ID) REFERENCES EMP_EMPRESA (EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CXA_CAIXA(
	CXA_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CXA_STATUS INT(20),
	EMP_ID BIGINT UNSIGNED NOT NULL,
	ARQ_ID BIGINT UNSIGNED,
	CONSTRAINT CXA_CAIXA_PK PRIMARY KEY (CXA_ID),
	FOREIGN KEY EMP_EMPRESA_FK (EMP_ID) REFERENCES EMP_EMPRESA (EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY ARQ_ARQUIVO_FK (ARQ_ID) REFERENCES ARQ_ARQUIVO (ARQ_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CXM_CAIXA_MASTER(
	CXM_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CXM_SLOTE INT(20),
	EMP_ID BIGINT UNSIGNED NOT NULL,
	CXA_ID BIGINT UNSIGNED,
	CONSTRAINT CXM_CAIXA_MASTER_PK PRIMARY KEY (CXM_ID),
	FOREIGN KEY EMP_EMPRESA_FK (EMP_ID) REFERENCES EMP_EMPRESA (EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY CXA_CAIXA_FK (CXA_ID) REFERENCES CXA_CAIXA (CXA_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IMG_IMAGEM(
	IMG_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	IMG_CODIGO VARCHAR(500),
	ARQ_ID BIGINT UNSIGNED,
	CONSTRAINT IMG_IMAGEM_PK PRIMARY KEY (IMG_ID),
	FOREIGN KEY ARQ_ARQUIVO_FK (ARQ_ID) REFERENCES ARQ_ARQUIVO (ARQ_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE CPR_CALCULO_PROJETO(
	CPR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	CONSTRAINT CPR_CALCULO_PROJETO_PK PRIMARY KEY (CPR_ID)
);


CREATE TABLE END_ENDERECO(
	END_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	END_RUA INT,
	END_ESTANTE INT,
	END_PRATELEIRA INT,
	END_PV INT,
	END_PH INT,
	CXM_ID BIGINT UNSIGNED NOT NULL,
	EMP_ID BIGINT UNSIGNED NOT NULL,
	CONSTRAINT END_ENDERECO_PK PRIMARY KEY (END_ID),
	FOREIGN KEY CXM_CAIXA_MASTER_FK (CXM_ID) REFERENCES CXM_CAIXA_MASTER (CXM_ID) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY EMP_EMPRESA_FK (EMP_ID) REFERENCES EMP_EMPRESA (EMP_ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
	

